/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrental.admin;

import carrental.auth.Login;
import java.awt.Color;

/**
 *
 * @author user
 */
public class AdminMain extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    Color defaultColor, clickedColor;

    public AdminMain() {
        initComponents();
        defaultColor = new Color(51, 51, 255);
        clickedColor = new Color(51, 102, 255);
        ManageCarPanel.setBackground(clickedColor);
        ManageBookingPanel.setBackground(defaultColor);
        ManageCar manageCar = new ManageCar();
        jDesktopPane.removeAll();
        jDesktopPane.add(manageCar).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitBtn = new javax.swing.JButton();
        AdminPanel = new javax.swing.JPanel();
        ManageCarPanel = new javax.swing.JPanel();
        ManageCarText = new javax.swing.JLabel();
        ManageBookingPanel = new javax.swing.JPanel();
        ManageCar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(220, 53, 69));
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Logout");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        exitBtn.setFocusable(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 90, 30));

        AdminPanel.setBackground(new java.awt.Color(51, 51, 255));
        AdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageCarPanel.setToolTipText("");
        ManageCarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageCarPanelMousePressed(evt);
            }
        });
        ManageCarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageCarText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ManageCarText.setForeground(new java.awt.Color(255, 255, 255));
        ManageCarText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManageCarText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/Car-2-icon.png"))); // NOI18N
        ManageCarText.setText(" Manage Car");
        ManageCarText.setMaximumSize(new java.awt.Dimension(20, 20));
        ManageCarText.setMinimumSize(new java.awt.Dimension(20, 20));
        ManageCarText.setPreferredSize(new java.awt.Dimension(20, 20));
        ManageCarPanel.add(ManageCarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        AdminPanel.add(ManageCarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 40));

        ManageBookingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageBookingPanelMousePressed(evt);
            }
        });
        ManageBookingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageCar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ManageCar1.setForeground(new java.awt.Color(255, 255, 255));
        ManageCar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/Mimetypes-application-pgp-signature-icon.png"))); // NOI18N
        ManageCar1.setText(" Manage Booking");
        ManageBookingPanel.add(ManageCar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        AdminPanel.add(ManageBookingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/1.png"))); // NOI18N
        AdminPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 90));

        getContentPane().add(AdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));
        getContentPane().add(jDesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 830, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void ManageCarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCarPanelMousePressed
        ManageCarPanel.setBackground(clickedColor);
        ManageBookingPanel.setBackground(defaultColor);
        ManageCar manageCar = new ManageCar();
        jDesktopPane.removeAll();
        jDesktopPane.add(manageCar).setVisible(true);
    }//GEN-LAST:event_ManageCarPanelMousePressed

    private void ManageBookingPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBookingPanelMousePressed
        ManageCarPanel.setBackground(defaultColor);
        ManageBookingPanel.setBackground(clickedColor);
        ManageBooking ManageBooking = new ManageBooking();
        jDesktopPane.removeAll();
        jDesktopPane.add(ManageBooking).setVisible(true);
    }//GEN-LAST:event_ManageBookingPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel ManageBookingPanel;
    private javax.swing.JLabel ManageCar1;
    private javax.swing.JPanel ManageCarPanel;
    private javax.swing.JLabel ManageCarText;
    private javax.swing.JButton exitBtn;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
