/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrental.admin;

import carrental.Admin;
import carrental.Car;
import carrental.admin.ManageCar;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class EditCar extends javax.swing.JFrame {

    /**
     * Creates new form EditCar
     */
    public EditCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editCarBtn = new javax.swing.JButton();
        EditCarText = new javax.swing.JLabel();
        carBrandText = new javax.swing.JLabel();
        carModelText = new javax.swing.JLabel();
        carColorText = new javax.swing.JLabel();
        carYearText = new javax.swing.JLabel();
        carPriceText = new javax.swing.JLabel();
        carBrandField = new javax.swing.JTextField();
        carModelField = new javax.swing.JTextField();
        carColorField = new javax.swing.JTextField();
        carYearField = new javax.swing.JTextField();
        carPriceField = new javax.swing.JTextField();
        mainBtn = new javax.swing.JButton();
        carIDField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 650));
        setPreferredSize(new java.awt.Dimension(1050, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editCarBtn.setBackground(new java.awt.Color(25, 135, 84));
        editCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        editCarBtn.setText("Edit Car");
        editCarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        editCarBtn.setFocusable(false);
        editCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 130, 40));

        EditCarText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        EditCarText.setForeground(new java.awt.Color(255, 255, 255));
        EditCarText.setText("Edit Car");
        getContentPane().add(EditCarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 200, 30));

        carBrandText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carBrandText.setForeground(new java.awt.Color(255, 255, 255));
        carBrandText.setText("Car Brand");
        getContentPane().add(carBrandText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, 20));

        carModelText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carModelText.setForeground(new java.awt.Color(255, 255, 255));
        carModelText.setText("Car Model");
        getContentPane().add(carModelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, 20));

        carColorText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carColorText.setForeground(new java.awt.Color(255, 255, 255));
        carColorText.setText("Car Color");
        getContentPane().add(carColorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, 20));

        carYearText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carYearText.setForeground(new java.awt.Color(255, 255, 255));
        carYearText.setText("Car Year");
        getContentPane().add(carYearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, 20));

        carPriceText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carPriceText.setForeground(new java.awt.Color(255, 255, 255));
        carPriceText.setText("Car Price");
        getContentPane().add(carPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, 20));

        carBrandField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carBrandField.setForeground(new java.awt.Color(255, 255, 255));
        carBrandField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carBrandField.setOpaque(false);
        carBrandField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBrandFieldActionPerformed(evt);
            }
        });
        carBrandField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carBrandFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carBrandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 300, 40));

        carModelField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carModelField.setForeground(new java.awt.Color(255, 255, 255));
        carModelField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carModelField.setOpaque(false);
        carModelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carModelFieldActionPerformed(evt);
            }
        });
        carModelField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carModelFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carModelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 300, 40));

        carColorField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carColorField.setForeground(new java.awt.Color(255, 255, 255));
        carColorField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carColorField.setOpaque(false);
        carColorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carColorFieldActionPerformed(evt);
            }
        });
        carColorField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carColorFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carColorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 300, 40));

        carYearField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carYearField.setForeground(new java.awt.Color(255, 255, 255));
        carYearField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carYearField.setOpaque(false);
        carYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carYearFieldActionPerformed(evt);
            }
        });
        carYearField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carYearFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carYearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 300, 40));

        carPriceField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carPriceField.setForeground(new java.awt.Color(255, 255, 255));
        carPriceField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carPriceField.setOpaque(false);
        carPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPriceFieldActionPerformed(evt);
            }
        });
        carPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carPriceFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 300, 40));

        mainBtn.setBackground(new java.awt.Color(220, 53, 69));
        mainBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn.setText("Back to Main");
        mainBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        mainBtn.setFocusable(false);
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 130, 40));

        carIDField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carIDField.setForeground(new java.awt.Color(255, 255, 255));
        carIDField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carIDField.setOpaque(false);
        carIDField.setVisible(false);
        carIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carIDFieldActionPerformed(evt);
            }
        });
        carIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carIDFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 10, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCarBtnActionPerformed
        String carID, carBrand, carModel, carColor, carYear, carRentPrice;
        carID = carIDField.getText().trim();
        carBrand = carBrandField.getText().trim();
        carModel = carModelField.getText().trim();
        carColor = carColorField.getText().trim();
        carYear = carYearField.getText().trim();
        carRentPrice = carPriceField.getText().trim();
        
        Car car = new Car(carID, carBrand, carModel, carColor, carYear, carRentPrice);
        Admin admin = new Admin(car);
        admin.editCar(this);
        
    }//GEN-LAST:event_editCarBtnActionPerformed

    private void carBrandFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBrandFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBrandFieldActionPerformed

    private void carBrandFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carBrandFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBrandFieldKeyPressed

    private void carModelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carModelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carModelFieldActionPerformed

    private void carModelFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carModelFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carModelFieldKeyPressed

    private void carColorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carColorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carColorFieldActionPerformed

    private void carColorFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carColorFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carColorFieldKeyPressed

    private void carYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carYearFieldActionPerformed

    private void carYearFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carYearFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carYearFieldKeyPressed

    private void carPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPriceFieldActionPerformed

    private void carPriceFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carPriceFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPriceFieldKeyPressed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        ManageCar manageCar = new ManageCar();
        manageCar.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainBtnActionPerformed

    private void carIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carIDFieldActionPerformed

    private void carIDFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carIDFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carIDFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EditCarText;
    public javax.swing.JTextField carBrandField;
    private javax.swing.JLabel carBrandText;
    public javax.swing.JTextField carColorField;
    private javax.swing.JLabel carColorText;
    public javax.swing.JTextField carIDField;
    public javax.swing.JTextField carModelField;
    private javax.swing.JLabel carModelText;
    public javax.swing.JTextField carPriceField;
    private javax.swing.JLabel carPriceText;
    public javax.swing.JTextField carYearField;
    private javax.swing.JLabel carYearText;
    private javax.swing.JButton editCarBtn;
    private javax.swing.JButton mainBtn;
    // End of variables declaration//GEN-END:variables
}
