/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package carrental.admin;

import carrental.Admin;
import carrental.Car;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class ManageCar extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManageCarFrame
     */
    public ManageCar() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        carTable.removeColumn(carTable.getColumnModel().getColumn(1));
        Show_Table();
    }

    private void Show_Table() {
        carTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        carTable.getTableHeader().setBackground(new Color(0, 0, 0, 150));
        carTable.getTableHeader().setForeground(new Color(255, 255, 255));
        carTablePane.setOpaque(false);
        carTablePane.getViewport().setOpaque(false);
        try {
            DefaultTableModel tableCar = (DefaultTableModel) carTable.getModel();
            BufferedReader brCar = new BufferedReader(new FileReader("car.txt"));
            Object[] carLines = brCar.lines().toArray();
            tableCar.setRowCount(0);
            for (int i = 0; i < carLines.length; i++) {
                String line = carLines[i].toString().trim();
                String record = i + 1 + "," + line;
                String[] row = record.split(",");
                tableCar.addRow(row);
            }
            brCar.close();
        } catch (Exception ecp) {
        }
    }

    private void filter(String filterSearch) {
        DefaultTableModel tableCar = (DefaultTableModel) carTable.getModel();
        TableRowSorter<DefaultTableModel> ts = new TableRowSorter<DefaultTableModel>(tableCar);
        carTable.setRowSorter(ts);

        ts.setRowFilter(RowFilter.regexFilter(filterSearch));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carTablePane = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        editCarBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        carBrandText = new javax.swing.JLabel();
        carModelText = new javax.swing.JLabel();
        carColorText = new javax.swing.JLabel();
        carBrandField = new javax.swing.JTextField();
        carModelField = new javax.swing.JTextField();
        carColorField = new javax.swing.JTextField();
        carYearText = new javax.swing.JLabel();
        carPriceText = new javax.swing.JLabel();
        carYearField = new javax.swing.JTextField();
        carPriceField = new javax.swing.JTextField();
        addNewCarText = new javax.swing.JLabel();
        createCarBtn = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        searchPanel = new javax.swing.JPanel();
        Search = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(830, 600));
        setPreferredSize(new java.awt.Dimension(830, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carTablePane.setBackground(new java.awt.Color(255, 255, 255));
        carTablePane.setBorder(null);

        carTable.setBackground(new java.awt.Color(255, 255, 255, 230));
        carTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Car ID", "Car Brand", "Car Model", "Car Color", "Car Year", "Car Price", "CarStatus"
            }
        ));
        carTable.setFocusable(false);
        carTable.setGridColor(new java.awt.Color(255, 255, 255));
        carTable.setIntercellSpacing(new java.awt.Dimension(0, 1));
        carTable.setOpaque(false);
        carTable.setRowHeight(35);
        carTable.setSelectionBackground(new java.awt.Color(102, 153, 255));
        carTable.setShowGrid(true);
        carTable.setShowVerticalLines(false);
        carTable.getTableHeader().setReorderingAllowed(false);
        carTablePane.setViewportView(carTable);

        getContentPane().add(carTablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 720, 280));

        editCarBtn.setBackground(new java.awt.Color(25, 135, 84));
        editCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        editCarBtn.setText("Edit Car");
        editCarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        editCarBtn.setFocusable(false);
        editCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 110, 40));

        deleteBtn.setBackground(new java.awt.Color(255, 51, 0));
        deleteBtn.setForeground(new java.awt.Color(255, 51, 0));
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(null);
        deleteBtn.setFocusable(false);
        deleteBtn.setOpaque(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 90, 40));

        carBrandText.setBackground(new java.awt.Color(255, 255, 255));
        carBrandText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carBrandText.setText("Car Brand");
        getContentPane().add(carBrandText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        carModelText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carModelText.setText("Car Model");
        getContentPane().add(carModelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        carColorText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carColorText.setText("Car Color");
        getContentPane().add(carColorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 20));

        carBrandField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carBrandField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        carBrandField.setOpaque(false);
        carBrandField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBrandFieldActionPerformed(evt);
            }
        });
        carBrandField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carBrandFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carBrandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 210, 40));

        carModelField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carModelField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        carModelField.setOpaque(false);
        carModelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carModelFieldActionPerformed(evt);
            }
        });
        carModelField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carModelFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carModelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, 40));

        carColorField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carColorField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        carColorField.setOpaque(false);
        carColorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carColorFieldActionPerformed(evt);
            }
        });
        carColorField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carColorFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carColorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 210, 40));

        carYearText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carYearText.setText("Car Year");
        getContentPane().add(carYearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, 20));

        carPriceText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carPriceText.setText("Car Price");
        getContentPane().add(carPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, 20));

        carYearField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carYearField.setForeground(new java.awt.Color(255, 255, 255));
        carYearField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        carYearField.setOpaque(false);
        carYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carYearFieldActionPerformed(evt);
            }
        });
        carYearField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carYearFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carYearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 210, 40));

        carPriceField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carPriceField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        carPriceField.setOpaque(false);
        carPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPriceFieldActionPerformed(evt);
            }
        });
        carPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carPriceFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 210, 40));

        addNewCarText.setBackground(new java.awt.Color(255, 255, 255));
        addNewCarText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        addNewCarText.setForeground(new java.awt.Color(51, 153, 255));
        addNewCarText.setText("Add New Car");
        getContentPane().add(addNewCarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 40));

        createCarBtn.setBackground(new java.awt.Color(25, 135, 84));
        createCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        createCarBtn.setText("Add Car");
        createCarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        createCarBtn.setFocusable(false);
        createCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 130, 40));

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 240, 30));

        searchPanel.setBackground(new java.awt.Color(204, 204, 204));

        Search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Search.setText("Search");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCarBtnActionPerformed

        //        ArrayList<String> carList = new ArrayList<>();
        try {
            if (carTable.getSelectedRowCount() == 1) {
                DefaultTableModel tableCar = (DefaultTableModel) carTable.getModel();
                int i = carTable.getSelectedRow();
                String carID = tableCar.getValueAt(i, 1).toString();
                String carBrand = tableCar.getValueAt(i, 2).toString();
                String carModel = tableCar.getValueAt(i, 3).toString();
                String carColor = tableCar.getValueAt(i, 4).toString();
                String carYear = tableCar.getValueAt(i, 5).toString();
                String carRentPrice = tableCar.getValueAt(i, 6).toString();
                String carStatus = tableCar.getValueAt(i, 7).toString();

                if (carStatus.equals("Unavailable")) {
                    JOptionPane.showMessageDialog(this, "Rent Out Car should not be edited");
                } else {

                    EditCar editCar = new EditCar();
                    editCar.setVisible(true);
                    editCar.setLocationRelativeTo(null);

                    editCar.carIDField.setText(carID);
                    editCar.carBrandField.setText(carBrand);
                    editCar.carModelField.setText(carModel);
                    editCar.carColorField.setText(carColor);
                    editCar.carYearField.setText(carYear);
                    editCar.carPriceField.setText(carRentPrice);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a record to edit");
            }

        } catch (Exception ecp) {
            System.out.println("Something went Wrong");
        }
    }//GEN-LAST:event_editCarBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        Admin admin = new Admin();
        admin.deleteCar(carTable, this);
        Show_Table();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void carBrandFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBrandFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBrandFieldActionPerformed

    private void carBrandFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carBrandFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBrandFieldKeyPressed

    private void carModelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carModelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carModelFieldActionPerformed

    private void carModelFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carModelFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carModelFieldKeyPressed

    private void carColorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carColorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carColorFieldActionPerformed

    private void carColorFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carColorFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carColorFieldKeyPressed

    private void carYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carYearFieldActionPerformed

    private void carYearFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carYearFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carYearFieldKeyPressed

    private void carPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPriceFieldActionPerformed

    private void carPriceFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carPriceFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPriceFieldKeyPressed

    private void createCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCarBtnActionPerformed
        String carBrand, carModel, carColor, carYear, carRentPrice;

        carBrand = carBrandField.getText().trim();
        carModel = carModelField.getText().trim();
        carColor = carColorField.getText().trim();
        carYear = carYearField.getText().trim();
        carRentPrice = carPriceField.getText().trim();

        Car car = new Car(carBrand, carModel, carColor, carYear, carRentPrice);
        Admin admin = new Admin(car);
        admin.createCar();
        Show_Table();
    }//GEN-LAST:event_createCarBtnActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        String filterSearch = search.getText();
        filter(filterSearch);
    }//GEN-LAST:event_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search;
    private javax.swing.JLabel addNewCarText;
    public javax.swing.JTextField carBrandField;
    private javax.swing.JLabel carBrandText;
    public javax.swing.JTextField carColorField;
    private javax.swing.JLabel carColorText;
    public javax.swing.JTextField carModelField;
    private javax.swing.JLabel carModelText;
    public javax.swing.JTextField carPriceField;
    private javax.swing.JLabel carPriceText;
    private javax.swing.JTable carTable;
    private javax.swing.JScrollPane carTablePane;
    public javax.swing.JTextField carYearField;
    private javax.swing.JLabel carYearText;
    private javax.swing.JButton createCarBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editCarBtn;
    private javax.swing.JTextField search;
    private javax.swing.JPanel searchPanel;
    // End of variables declaration//GEN-END:variables
}
