/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrental.customer;

import carrental.Customer;
import carrental.admin.ManageCar;
import carrental.auth.Login;
import java.awt.Color;

/**
 *
 * @author user
 */
public class CustomerMain extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Color defaultColor, clickedColor;

    public CustomerMain() {
        initComponents();
        defaultColor = new Color(51, 51, 255);
        clickedColor = new Color(51, 102, 255);
        RentCarPanel.setBackground(clickedColor);
        paymentPanel.setBackground(defaultColor);
        rentingCarPanel.setBackground(defaultColor);
        Customer customer = new Customer();
        customerNameText.setText(customer.getUserName());
        ViewAllCar viewAllCar = new ViewAllCar();
        jDesktopPane.removeAll();
        jDesktopPane.add(viewAllCar).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerIDText = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        RentCarPanel = new javax.swing.JPanel();
        RentCarText = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        paymentText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rentingCarPanel = new javax.swing.JPanel();
        rentingCarText = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        customerNameText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1050, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerIDText.setVisible(false);
        getContentPane().add(customerIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        AdminPanel.setBackground(new java.awt.Color(51, 51, 255));
        AdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RentCarPanel.setToolTipText("");
        RentCarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RentCarPanelMousePressed(evt);
            }
        });
        RentCarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RentCarText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RentCarText.setForeground(new java.awt.Color(255, 255, 255));
        RentCarText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RentCarText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/Car-2-icon.png"))); // NOI18N
        RentCarText.setText(" Rent Car");
        RentCarText.setMaximumSize(new java.awt.Dimension(20, 20));
        RentCarText.setMinimumSize(new java.awt.Dimension(20, 20));
        RentCarText.setPreferredSize(new java.awt.Dimension(20, 20));
        RentCarPanel.add(RentCarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        AdminPanel.add(RentCarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 40));

        paymentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paymentPanelMousePressed(evt);
            }
        });
        paymentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paymentText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentText.setForeground(new java.awt.Color(255, 255, 255));
        paymentText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/Mimetypes-application-pgp-signature-icon.png"))); // NOI18N
        paymentText.setText(" Make Payment");
        paymentPanel.add(paymentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        AdminPanel.add(paymentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/1.png"))); // NOI18N
        AdminPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 90));

        rentingCarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rentingCarPanelMousePressed(evt);
            }
        });
        rentingCarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rentingCarText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rentingCarText.setForeground(new java.awt.Color(255, 255, 255));
        rentingCarText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/Mimetypes-application-pgp-signature-icon.png"))); // NOI18N
        rentingCarText.setText("Your Renting Car");
        rentingCarPanel.add(rentingCarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        AdminPanel.add(rentingCarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, 40));

        getContentPane().add(AdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));
        getContentPane().add(jDesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 830, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/icons8-alarm-24.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/icons8-logout-24.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 30, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/Image/icons8-user-34.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        customerNameText.setText("Customer");
        jPanel1.add(customerNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 830, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RentCarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentCarPanelMousePressed
        RentCarPanel.setBackground(clickedColor);
        paymentPanel.setBackground(defaultColor);
        rentingCarPanel.setBackground(defaultColor);
        ViewAllCar viewAllCar = new ViewAllCar();
        jDesktopPane.removeAll();
        jDesktopPane.add(viewAllCar).setVisible(true);
    }//GEN-LAST:event_RentCarPanelMousePressed

    private void paymentPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentPanelMousePressed
        RentCarPanel.setBackground(defaultColor);
        paymentPanel.setBackground(clickedColor);
        rentingCarPanel.setBackground(defaultColor);
        ViewPayment viewPayment = new ViewPayment();
        jDesktopPane.removeAll();
        jDesktopPane.add(viewPayment).setVisible(true);
    }//GEN-LAST:event_paymentPanelMousePressed

    private void rentingCarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentingCarPanelMousePressed
        RentCarPanel.setBackground(defaultColor);
        paymentPanel.setBackground(defaultColor);
        rentingCarPanel.setBackground(clickedColor);
        ViewRentingCar viewRentingCar = new ViewRentingCar();
        jDesktopPane.removeAll();
        jDesktopPane.add(viewRentingCar).setVisible(true);
    }//GEN-LAST:event_rentingCarPanelMousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jLabel4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel RentCarPanel;
    private javax.swing.JLabel RentCarText;
    public static javax.swing.JLabel customerIDText;
    public javax.swing.JLabel customerNameText;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel paymentText;
    private javax.swing.JPanel rentingCarPanel;
    private javax.swing.JLabel rentingCarText;
    // End of variables declaration//GEN-END:variables
}
