/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrental.customer;

import carrental.Booking;
import carrental.Car;
import carrental.Customer;
import carrental.User;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class RentCar extends javax.swing.JFrame {

    /**
     * Creates new form RentCar
     */
    public RentCar() {
        initComponents();
        carBrandField.setEditable(false);
        carModelField.setEditable(false);
        carColorField.setEditable(false);
        carYearField.setEditable(false);
        carPriceField.setEditable(false);
        totalPriceField.setEditable(false);
        totalRentDayField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RentCarText = new javax.swing.JLabel();
        carBrandText = new javax.swing.JLabel();
        carBrandField = new javax.swing.JTextField();
        carModelText = new javax.swing.JLabel();
        carModelField = new javax.swing.JTextField();
        carColorText = new javax.swing.JLabel();
        carColorField = new javax.swing.JTextField();
        carYearText = new javax.swing.JLabel();
        carYearField = new javax.swing.JTextField();
        carPriceText = new javax.swing.JLabel();
        carPriceField = new javax.swing.JTextField();
        rentOutDateText = new javax.swing.JLabel();
        rentOutDateField = new com.toedter.calendar.JDateChooser();
        returnDateText = new javax.swing.JLabel();
        returnDateField = new com.toedter.calendar.JDateChooser();
        totalRentDayText = new javax.swing.JLabel();
        totalRentDayField = new javax.swing.JTextField();
        totalPriceText = new javax.swing.JLabel();
        totalPriceField = new javax.swing.JTextField();
        mainBtn = new javax.swing.JButton();
        bookBtn = new javax.swing.JButton();
        carIDField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1050, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RentCarText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        RentCarText.setForeground(new java.awt.Color(255, 255, 255));
        RentCarText.setText("Rent Car");
        getContentPane().add(RentCarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 230, 60));

        carBrandText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carBrandText.setForeground(new java.awt.Color(255, 255, 255));
        carBrandText.setText("Car Brand");
        getContentPane().add(carBrandText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, 20));

        carBrandField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carBrandField.setForeground(new java.awt.Color(255, 255, 255));
        carBrandField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carBrandField.setOpaque(false);
        carBrandField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBrandFieldActionPerformed(evt);
            }
        });
        carBrandField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carBrandFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carBrandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 240, 40));

        carModelText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carModelText.setForeground(new java.awt.Color(255, 255, 255));
        carModelText.setText("Car Model");
        getContentPane().add(carModelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        carModelField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carModelField.setForeground(new java.awt.Color(255, 255, 255));
        carModelField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carModelField.setOpaque(false);
        carModelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carModelFieldActionPerformed(evt);
            }
        });
        carModelField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carModelFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carModelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 240, 40));

        carColorText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carColorText.setForeground(new java.awt.Color(255, 255, 255));
        carColorText.setText("Car Color");
        getContentPane().add(carColorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        carColorField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carColorField.setForeground(new java.awt.Color(255, 255, 255));
        carColorField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carColorField.setOpaque(false);
        carColorField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                carColorFieldMousePressed(evt);
            }
        });
        carColorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carColorFieldActionPerformed(evt);
            }
        });
        carColorField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carColorFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carColorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 240, 40));

        carYearText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carYearText.setForeground(new java.awt.Color(255, 255, 255));
        carYearText.setText("Car Year");
        getContentPane().add(carYearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        carYearField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carYearField.setForeground(new java.awt.Color(255, 255, 255));
        carYearField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carYearField.setOpaque(false);
        carYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carYearFieldActionPerformed(evt);
            }
        });
        getContentPane().add(carYearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 240, 40));

        carPriceText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        carPriceText.setForeground(new java.awt.Color(255, 255, 255));
        carPriceText.setText("Car Price");
        getContentPane().add(carPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        carPriceField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carPriceField.setForeground(new java.awt.Color(255, 255, 255));
        carPriceField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carPriceField.setOpaque(false);
        carPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPriceFieldActionPerformed(evt);
            }
        });
        carPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carPriceFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 260, 40));

        rentOutDateText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        rentOutDateText.setForeground(new java.awt.Color(255, 255, 255));
        rentOutDateText.setText("Rent Out Date");
        getContentPane().add(rentOutDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        rentOutDateField.setBackground(new java.awt.Color(0, 0, 0));
        rentOutDateField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 2, true));
        rentOutDateField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rentOutDateFieldPropertyChange(evt);
            }
        });
        getContentPane().add(rentOutDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 260, 40));

        returnDateText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        returnDateText.setForeground(new java.awt.Color(255, 255, 255));
        returnDateText.setText("Return Date");
        getContentPane().add(returnDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        returnDateField.setBackground(new java.awt.Color(0, 0, 0));
        returnDateField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 2, true));
        returnDateField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                returnDateFieldPropertyChange(evt);
            }
        });
        getContentPane().add(returnDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 260, 40));

        totalRentDayText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        totalRentDayText.setForeground(new java.awt.Color(255, 255, 255));
        totalRentDayText.setText("Total Day Of Rent");
        getContentPane().add(totalRentDayText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));

        totalRentDayField.setForeground(new java.awt.Color(255, 255, 255));
        totalRentDayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalRentDayField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        totalRentDayField.setOpaque(false);
        totalRentDayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalRentDayFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalRentDayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 120, 40));

        totalPriceText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        totalPriceText.setForeground(new java.awt.Color(255, 255, 255));
        totalPriceText.setText("Total Price");
        getContentPane().add(totalPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 70, -1));

        totalPriceField.setForeground(new java.awt.Color(255, 255, 255));
        totalPriceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPriceField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        totalPriceField.setOpaque(false);
        totalPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 120, 40));

        mainBtn.setBackground(new java.awt.Color(220, 53, 69));
        mainBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn.setText("Back to Main");
        mainBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        mainBtn.setFocusable(false);
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 110, 40));

        bookBtn.setBackground(new java.awt.Color(25, 135, 84));
        bookBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookBtn.setText("Book");
        bookBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        bookBtn.setFocusable(false);
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 110, 40));

        carIDField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carIDField.setForeground(new java.awt.Color(255, 255, 255));
        carIDField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        carIDField.setOpaque(false);
        carIDField.setVisible(false);
        carIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carIDFieldActionPerformed(evt);
            }
        });
        carIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carIDFieldKeyPressed(evt);
            }
        });
        getContentPane().add(carIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 20, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentOutDateFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rentOutDateFieldPropertyChange
        try {
            Date rentOutDate = rentOutDateField.getDate();
            Date returnDate = returnDateField.getDate();
            String carPriceString = carPriceField.getText().toString();
            double carPrice = Double.parseDouble(carPriceString);
            if (rentOutDate != null) {
                returnDateField.setEnabled(rootPaneCheckingEnabled);
                returnDateField.setMinSelectableDate(rentOutDate);
            }
            if (returnDate != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH.mm");
                Date cID = rentOutDateField.getDate();
                Date cOD = returnDateField.getDate();

                long ms = Math.abs(cID.getTime() - cOD.getTime());
                long days = TimeUnit.DAYS.convert(ms, TimeUnit.MILLISECONDS);

                totalRentDayField.setText(Long.toString(days) + " day ");
                double totalRentPrice;
                totalRentPrice = days * carPrice;

                totalPriceField.setText("RM " + String.valueOf(totalRentPrice));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rentOutDateFieldPropertyChange

    private void returnDateFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_returnDateFieldPropertyChange
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH.mm");
            Date cID = rentOutDateField.getDate();
            Date cOD = returnDateField.getDate();
            String carPriceString = carPriceField.getText().toString();
            double carPrice = Double.parseDouble(carPriceString);

            long ms = Math.abs(cID.getTime() - cOD.getTime());
            long days = TimeUnit.DAYS.convert(ms, TimeUnit.MILLISECONDS);

            totalRentDayField.setText(Long.toString(days) + " day ");
            double totalRentPrice;
            totalRentPrice = days * carPrice;

            totalPriceField.setText("RM " + String.valueOf(totalRentPrice));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_returnDateFieldPropertyChange

    private void totalRentDayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalRentDayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalRentDayFieldActionPerformed

    private void totalPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPriceFieldActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        String carID = carIDField.getText().toString();
        String carBrand = carBrandField.getText().toString();
        String carModel = carModelField.getText().toString();
        String carColor = carColorField.getText().toString();
        String carYear= carYearField.getText().toString();
        String carPrice = carPriceField.getText().toString();
        String totalRentPrice = totalPriceField.getText().toString();
        Date cID = rentOutDateField.getDate();
        Date cOD = returnDateField.getDate();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        String rentOutDate = simpleDateFormat.format(cID);
        String returnDate = simpleDateFormat.format(cOD);
        String bookingStatus = "pending";

        Car car = new Car(carID, carBrand, carModel, carColor, carYear, carPrice);
        Booking booking = new Booking(bookingStatus, rentOutDate, returnDate, totalRentPrice);
        Customer customer = new Customer(car, booking);
        customer.rentCar(this);
        
        dispose();
    }//GEN-LAST:event_bookBtnActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
//        CustomerMain customerMain = new CustomerMain();
//        customerMain.customerNameText.setText(customerNameText.getText());
//        customerMain.customerIDText.setText(customerIDText.getText());
//        customerMain.setVisible(true);
//        customerMain.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_mainBtnActionPerformed

    private void carPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPriceFieldActionPerformed

    private void carPriceFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carPriceFieldKeyPressed

    }//GEN-LAST:event_carPriceFieldKeyPressed

    private void carModelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carModelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carModelFieldActionPerformed

    private void carModelFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carModelFieldKeyPressed

    }//GEN-LAST:event_carModelFieldKeyPressed

    private void carColorFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carColorFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carColorFieldMousePressed

    private void carColorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carColorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carColorFieldActionPerformed

    private void carColorFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carColorFieldKeyPressed

    }//GEN-LAST:event_carColorFieldKeyPressed

    private void carYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carYearFieldActionPerformed

    private void carBrandFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBrandFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBrandFieldActionPerformed

    private void carBrandFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carBrandFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBrandFieldKeyPressed

    private void carIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carIDFieldActionPerformed

    private void carIDFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carIDFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carIDFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RentCarText;
    private javax.swing.JButton bookBtn;
    public javax.swing.JTextField carBrandField;
    private javax.swing.JLabel carBrandText;
    public javax.swing.JTextField carColorField;
    private javax.swing.JLabel carColorText;
    public javax.swing.JTextField carIDField;
    public javax.swing.JTextField carModelField;
    private javax.swing.JLabel carModelText;
    public javax.swing.JTextField carPriceField;
    private javax.swing.JLabel carPriceText;
    public javax.swing.JTextField carYearField;
    private javax.swing.JLabel carYearText;
    private javax.swing.JButton mainBtn;
    public com.toedter.calendar.JDateChooser rentOutDateField;
    private javax.swing.JLabel rentOutDateText;
    public com.toedter.calendar.JDateChooser returnDateField;
    private javax.swing.JLabel returnDateText;
    public javax.swing.JTextField totalPriceField;
    private javax.swing.JLabel totalPriceText;
    public javax.swing.JTextField totalRentDayField;
    private javax.swing.JLabel totalRentDayText;
    // End of variables declaration//GEN-END:variables
}
