/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package carrental.customer;

import carrental.auth.Login;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewAllCar extends javax.swing.JInternalFrame {

    /**
     * Creates new form RentCar
     */
    public ViewAllCar() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        Show_Table();
        carTable.removeColumn(carTable.getColumnModel().getColumn(1));
        carTable.removeColumn(carTable.getColumnModel().getColumn(6));
    }

    private void Show_Table() {
        carTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        carTable.getTableHeader().setBackground(new Color(0, 0, 0, 150));
        carTable.getTableHeader().setForeground(new Color(255, 255, 255));
        carTablePane.setOpaque(false);
        carTablePane.getViewport().setOpaque(false);
        try {
            DefaultTableModel tableCar = (DefaultTableModel) carTable.getModel();
            BufferedReader brCar = new BufferedReader(new FileReader("car.txt"));
            Object[] carLines = brCar.lines().toArray();
            tableCar.setRowCount(0);
            int j = 1;
            for (int i = 0; i < carLines.length; i++) {
                String line = carLines[i].toString().trim();
                String[] row = line.split(",");
                if (row[6].equals("Available")) {
                    String record = j + "," + line;
                    String[] rowRecord = record.split(",");
                    tableCar.addRow(rowRecord);
                    j += 1;
                }
            }
            brCar.close();
        } catch (Exception ecp) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carTablePane = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        rentCarBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(830, 650));
        setPreferredSize(new java.awt.Dimension(830, 624));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carTablePane.setBackground(new java.awt.Color(255, 255, 255));
        carTablePane.setBorder(null);

        carTable.setBackground(new java.awt.Color(255, 255, 255, 230));
        carTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Car ID", "Car Brand", "Car Model", "Car Color", "Car Year", "Rent Price Per Day", "CarStatus"
            }
        ));
        carTable.setFocusable(false);
        carTable.setGridColor(new java.awt.Color(255, 255, 255));
        carTable.setIntercellSpacing(new java.awt.Dimension(0, 1));
        carTable.setOpaque(false);
        carTable.setRowHeight(35);
        carTable.setSelectionBackground(new java.awt.Color(102, 153, 255));
        carTable.setShowGrid(true);
        carTable.setShowVerticalLines(false);
        carTable.getTableHeader().setReorderingAllowed(false);
        carTablePane.setViewportView(carTable);

        getContentPane().add(carTablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 750, 380));

        rentCarBtn.setBackground(new java.awt.Color(25, 135, 84));
        rentCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        rentCarBtn.setText("Proceed To Booking");
        rentCarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        rentCarBtn.setFocusable(false);
        rentCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rentCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarBtnActionPerformed

        try {
            if (carTable.getSelectedRowCount() == 1) {
                DefaultTableModel tableCar = (DefaultTableModel) carTable.getModel();
                int i = carTable.getSelectedRow();
                String carID = tableCar.getValueAt(i, 1).toString();
                String carBrand = tableCar.getValueAt(i, 2).toString();
                String carModel = tableCar.getValueAt(i, 3).toString();
                String carColor = tableCar.getValueAt(i, 4).toString();
                String carYear = tableCar.getValueAt(i, 5).toString();
                String carPrice = tableCar.getValueAt(i, 6).toString();
                String carStatus = tableCar.getValueAt(i, 7).toString();

                RentCar rentCar = new RentCar();
                rentCar.setVisible(true);
                rentCar.setLocationRelativeTo(null);

                rentCar.carIDField.setText(carID);
                rentCar.carBrandField.setText(carBrand);
                rentCar.carModelField.setText(carModel);
                rentCar.carColorField.setText(carColor);
                rentCar.carYearField.setText(carYear);
                rentCar.carPriceField.setText(carPrice);

            } else {
                JOptionPane.showMessageDialog(this, "Please select a record to edit");
            }

        } catch (Exception ecp) {
            System.out.println("Something went Wrong");
        }
    }//GEN-LAST:event_rentCarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable carTable;
    private javax.swing.JScrollPane carTablePane;
    private javax.swing.JButton rentCarBtn;
    // End of variables declaration//GEN-END:variables
}
